{% set name = "kastore" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e62c506aa553895573e169f67ee9d4c1889182a3627a50108760352c3f8df85e

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - kastore=kastore.__main__:main

# Following the guidance here for building against numpy:
# https://conda-forge.org/docs/meta.html#building-against-numpy
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - python
    - pip
    - numpy
  run:
    - setuptools
    - python
    - importlib_metadata
    - six
    - humanize

test:
  imports:
    - kastore

  commands:
    - kastore --help

about:
  home: http://github.com/kastore/kastore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Write-once-read-many key-array store
  description: Simple key-value store for arrays of numerical data.
  doc_url: http://kastore.readthedocs.io/en/stable
  dev_url: https://github.com/tskit-dev/kastore

extra:
  recipe-maintainers:
    - jeromekelleher
