travis:
  secure:
    BINSTAR_TOKEN: YtjzRnURh6yLbClDXwEU7IAMHyNAiQO5HBJtatFieBQRYwa6c6rrtWL0KRP6tqxros2Fx9YaGZ5S/9dZpZl+RCotihEjtKgnAOfEANBq6wRXNH4HERlikz4kp7o0LI81JbF/k4IGtzv7+E0ElBVFYN/j6IPMn35Pg4oR6/hQFYqEwVvmVIVpV2tlsobY3Qp4wV5iHhOoyEfJOCrqO1SZoH5c0fXbQBwzoVPBC6s78BIHqnd02uNHfdOPQu4WXxKQVWC1oGruWCAEUwXc2lXfe9YIaPDjZ3ZjbvYcnlVi5Thz2lcW2jlQIJ1rSPo7MRzo7YIQ2fl3KS1qCfiy1MccnLbsu5hbxIRIyjrCwGl2gy0+xQKdK+K8YrtYvtBWE3+B9OEDjMfXDVlERgmIuQebMg30bs5Z5NIWY4X/Hp1/jou67FCF2rjKTZAM/JwsBXkv5Iz8EyhDnKzeAkeXTtFu5BrsaUTZrBStkxYKS0M2sbr0BGMbTBdx6TrBxp17R35AeKB8PZ2Z75PLmMWAgszdB+vS4LLKS3Abhl5T/RvolTLvCpOMxuVmHHD7cJdUIZq9HWHM2rc1jAi8kHfekIDqe0u3ANkqIYW5bzUPH8rZOrwP7bi0nLUsy2gQgQsj4K4GPoPzqx5ZCNtys4332WRG+B6Cuz2+3Ay/ipR1wTRhXtU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
